# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.3
# Mod Properties
mod_version=1.4.0
maven_group=dev.xef2
archives_base_name=visual-keymap
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.152.1+26.1.2
malilib_version=26.1.2:0.28.6
commandkeys_version=3.102.3+26.1.2
mod_menu_version=18.0.0-beta.1
