# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.4
# Mod Properties
mod_version=1.2.1
maven_group=dev.xef2
archives_base_name=visual-keymap
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.144.0+26.1
malilib_version=26.1:0.28.0
commandkeys_version=9nvEFnVd
mod_menu_version=18.0.0-alpha.6
