# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
loader_version=0.18.4
# Mod Properties
mod_version=1.2.1
maven_group=dev.xef2
archives_base_name=visual-keymap
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.3+1.21.11
malilib_version=1.21.11-0.27.7
commandkeys_version=8eiBV9Yy
mod_menu_version=17.0.0-beta.2
